GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/63672981a255b0781bf814d3

###

GET http://localhost:3001/todo/complete/63672981a255b0781bf814d3

###

PUT http://localhost:3001/todo/update/63672981a255b0781bf814d3
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}